config/routes.rb
MobileSample::Application.routes.draw do
  resources :notes

end

app/models/note.rb
class Note < ActiveRecord::Base
  attr_accessible :body, :title
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
 # respond_to_mobile_requests :skip_xhr_requests => false
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  # GET /notes
  # GET /notes.json
  def index
    @notes = Note.all

  
  end

  # GET /notes/1
  # GET /notes/1.json
  def show
    @note = Note.find(params[:id])

   
  end

  # GET /notes/new
  # GET /notes/new.json
  def new
    @note = Note.new

   
  end

  # GET /notes/1/edit
  def edit
    @note = Note.find(params[:id])
  end

  # POST /notes
  # POST /notes.json
  def create
    @note = Note.new(params[:note])

   # respond_to do |format|
      if @note.save
         redirect_to @note,notice: 'Note was successfully created.'
    #    format.html { redirect_to @note, notice: 'Note was successfully created.' }
    #    format.json { render json: @note, status: :created, location: @note }
      else
         render "new"
    #    format.html { render action: "new" }
     #   format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    #end
  end

  # PUT /notes/1
  # PUT /notes/1.json
  def update
    @note = Note.find(params[:id])

    #respond_to do |format|
      if @note.update_attributes(params[:note])
          redirect_to @note,notice: 'Note was successfully updated.'
    #    format.html { redirect_to @note, notice: 'Note was successfully updated.' }
     #   format.json { head :no_content }
      else
         render "new"
    #    format.html { render action: "edit" }
    #    format.json { render json: @note.errors, status: :unprocessable_entity }
      end
  #  end
  end

  # DELETE /notes/1
  # DELETE /notes/1.json
  def destroy
    @note = Note.find(params[:id])
    @note.destroy

   #respond_to do |format|
   #   format.html { redirect_to notes_url }
   #   format.json { head :no_content }
   # end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mobile Version!</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "jquery.mobile" %>
  <%= stylesheet_link_tag    "jquery.mobile.css" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div data-role="page">
  <%= yield %>
</div>
</body>
</html>

app/views/layouts/application.mobile.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mobile Version!</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "jquery.mobile.min" %>
  <%= stylesheet_link_tag    "jquery.mobile.min.css" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div data-role="page">
  <%= yield %>
</div>
</body>
</html>

app/views/notes/_form.html.erb
<div data-role="content">
  <%= form_for(@note) do |f| %>
    <% if @note.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@note.errors.count, "error") %> prohibited this note from being saved:</h2>
        <ul>
        <% @note.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <div class="field">
      <%= f.label :title %><br />
      <%= f.text_field :title %>
    </div>
    <div class="field">
      <%= f.label :body %><br />
      <%= f.text_area :body %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>
</div>

app/views/notes/edit.html.erb
<div data-role="header">
  <h1>Editing note</h1>
</div>
<%= render 'form' %>
<div data-role="footer">
  <%= link_to 'Show', @note %>
  <%= link_to 'Back', notes_path %>
</div>

app/views/notes/index.html.erb
<div data-role="header">
  <h1>Notes</h1>
</div>
<div data-role="content">
  <ul data-role="listview">
  <% @notes.each do |note| %>
    <li>
    <%= link_to note do %>
      <h2><%= note.title %></h2>
      <%= truncate(note.body, :length => 25) %>
    <% end %>
    </li>
  <% end %>
  </ul>
</div>
<div data-role="footer">
  <%= link_to 'New Note', new_note_path %>
</div>

app/views/notes/new.html.erb
<div data-role="header">
  <h1>New note</h1>
</div>
<%= render 'form' %>
<div data-role="footer">
  <%= link_to 'Back', notes_path %>
</div>

app/views/notes/show.html.erb
<div data-role="header">
  <h1><%= @note.title %></h1>
</div>
<div data-role="content">
  <p id="notice"><%= notice %></p>
  <p>
    <%= @note.body %>
  </p>
</div>
<div data-role="footer">
  <%= link_to 'Edit', edit_note_path(@note) %>
  <%= link_to 'Destroy', @note, confirm: 'Are you sure?', method: :delete %>
  <%= link_to 'Back', notes_path %>
</div>